### ISSUE TITLE
The Experimental Results on PPI?

### ISSUE THREAD

**Issue by mingloo** [yifan-h/CS-GNN#1]
Thanks for sharing the code! @yifan-h 

Do you have some experimental results comparing `CS-GNN` vs `GAT` on `PPI`?

**Comment by yifan-h** [comment]
Hi Ming,

Sorry we don't evaluate CS-GNN on PPI dataset. 

PPI dataset is composed of many small subgraphs. We cannot get the results for other models which don't support mini-batch. And our paper doesn't try to beat GAT with better attention mechanism. The main point is using two smoothness metrices to help researchers understand when and why GNNs work.

Besides, there are many interesting features of PPI dataset. The node features are fairly sparse, and we think they are generated by one-hot encoder. The attention coefficients are highly related to the cosine value of two connected nodes' features. There are many recent papers trying to figure out why GAT achieves significant performance on PPI. Hope you will find them helpful.

**Comment by mingloo** [comment]
Thanks for your prompt support.

Closed this issue now.
