### ISSUE TITLE
sorry to bother again。。

### ISSUE THREAD

**Issue by junkangwu** [yifan-h/CS-GNN#3]
I have try to normalize the feature of dataset cora. But it does'n work...
    The dataset -cora I used is in GCN(17-kipf), and I found its features are normalized in advance. It's so strange....
```
some data of trained feature of cora
  (0, 19)	1.0
  (0, 81)	1.0
  (0, 146)	1.0
  (0, 315)	1.0
  (0, 774)	1.0
  (0, 877)	1.0
  (0, 1194)	1.0
  (0, 1247)	1.0
  (0, 1274)	1.0
  (1, 19)	1.0
  (1, 88)	1.0
  (1, 149)	1.0
  (1, 212)	1.0
  (1, 233)	1.0
  (1, 332)	1.0
  (1, 336)	1.0
  (1, 359)	1.0
  (1, 472)	1.0
  (1, 507)	1.0
  (1, 548)	1.0
  (1, 687)	1.0
  (1, 763)	1.0
  (1, 808)	1.0
  (1, 889)	1.0
  (1, 1058)	1.0
  :	:
  (1706, 1236)	1.0
  (1706, 1242)	1.0
  (1706, 1320)	1.0
  (1706, 1337)	1.0
  (1707, 4)	1.0
  (1707, 118)	1.0
  (1707, 153)	1.0
  (1707, 180)	1.0
  (1707, 228)	1.0
  (1707, 699)	1.0
  (1707, 701)	1.0
  (1707, 719)	1.0
  (1707, 750)	1.0
  (1707, 758)	1.0
  (1707, 810)	1.0
  (1707, 911)	1.0
  (1707, 1177)	1.0
  (1707, 1233)	1.0
  (1707, 1251)	1.0
  (1707, 1257)	1.0
  (1707, 1262)	1.0
  (1707, 1299)	1.0
  (1707, 1325)	1.0
  (1707, 1386)	1.0
  (1707, 1397)	1.0
```

**Comment by yifan-h** [comment]
Oh, my mistake. May I ask if you compute the feature smoothness on the entire graph, or just for part of it?

**Comment by junkangwu** [comment]
Entire graph. Take cora for example, I compute it on 2708 nodes with 5429 edges.

**Comment by junkangwu** [comment]
There are my codes and results.
```
import numpy as np
import pickle as pkl
import networkx as nx
import scipy.sparse as sp
import sys

names = ['x', 'y', 'tx', 'ty', 'allx', 'ally', 'graph']
objects = []
for i in range(len(names)):
    with open("data/ind.{}.{}".format('cora', names[i]), 'rb') as f:
        if sys.version_info > (3, 0):
            objects.append(pkl.load(f, encoding='latin1'))
        else:
            objects.append(pkl.load(f))

x, y, tx, ty, allx, ally, graph = tuple(objects)

def parse_index_file(filename):
    """Parse index file."""
    index = []
    for line in open(filename):
        index.append(int(line.strip()))
    return index

test_idx_reorder = parse_index_file("data/ind.{}.test.index".format('cora'))
test_idx_range = np.sort(test_idx_reorder)

features = sp.vstack((allx, tx)).tolil()
features[test_idx_reorder, :] = features[test_idx_range, :]
adj = nx.adjacency_matrix(nx.from_dict_of_lists(graph))
features=features.toarray()

print(features.max())
print(features.min())
print(features.shape)
1.0
0.0
(2708, 1433)

print(features)
result=np.zeros(features.shape[1])
for i in range(features.shape[0]):
    z=np.zeros(features.shape[1])
    for j in range(features.shape[0]):
        if adj[i,j]==1 and i!=j:
            z+=features[i]-features[j]
    result+=z*z
result=np.sum(result)/(features.shape[1]*5429)
print(result)
​
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
0.248561233982
```

**Comment by yifan-h** [comment]
Hi there, I think I may know the problem. In our experiment, the realization of the feature smoothness is a bit different from that in the paper. For the computation efficiency, we take the square value of feature discrepancy for each neighbor, rather than for their sum value. If you change you code as 
'''

**Comment by yifan-h** [comment]
Hi there, I think I may know the problem. In our experiment, the realization of the feature smoothness is a bit different from that in the paper. For the computation efficiency, we take the square value of feature discrepancy for each neighbor, rather than for their sum value. If you change you code as
```
result=np.zeros(features.shape[1])
for i in range(features.shape[0]):
    z=np.zeros(features.shape[1])
    for j in range(features.shape[0]):
        if adj[i,j]==1 and i!=j:
            z+=(features[i]-features[j])*(features[i]-features[j])
    result+=z
result=np.sum(result)/(features.shape[1]*5429)
print(result)
```
Then you can get the same value.

Please note that for large-scale and sparse graphs, computing feature smoothness may spend too much time. Then for efficiency, we have to directly traverse the edges with aforementioned method to compute it.  

Hope it helps!

**Comment by junkangwu** [comment]
Thank a lot , I obtain the correct result aboue all. I also thought at first that there was some mistake in your formula.Because the square is more reasonable on the inside.
By the way, May I ask you about what is  the meaning of "aforementioned method"? Or  the method mentioned in the paper?

**Comment by yifan-h** [comment]
Oh, the aforementioned method is that we compute the feature smoothness by traversing the edge list, rather than relying on adjacency matrix or adjacency list, which is very convenient for large-scale graphs that cannot be loaded into memory at once.

**Comment by junkangwu** [comment]
I understand it！ Thanks for your detailed explaination!
Thank you so much !

**Comment by yifan-h** [comment]
Great! Then I'll close this issue.
