### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'node'

### ISSUE THREAD

**Issue by Aaron1993** [yifan-h/CS-GNN#5]
Hi. Yifan, when I run the code, there is a error:`AttributeError: 'Graph' object has no attribute 'node'` in such file: utils.py line 23: `if not 'val' in G.node[node] or not 'test' in G.node[node]:`, would you please tell me how to solve it? Thanks.

**Comment by yifan-h** [comment]
Hi there,

This error is caused by the version of "networkx". You can change the code from "G.node[node]" to "G.nodes[node]", or you can degrade networkx to an older version.

**Comment by Aaron1993** [comment]
Thanks for your prompt reply.
