### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'selfloop_edges'

### ISSUE THREAD

**Issue by Aaron1993** [yifan-h/CS-GNN#6]
Hi. yifan, sorry to disturb you again. There is a error `AttributeError: 'Graph' object has no attribute 'selfloop_edges'
` in utils.py: `        G.remove_edges_from(G.selfloop_edges())`, How can i to solve it? Thanks.

**Comment by yifan-h** [comment]
Hi Aaron, 

this is also a version issue of networkx. You may check it [here](https://stackoverflow.com/questions/49427638/removing-self-loops-from-undirected-networkx-graph) and try "G.remove_edges_from(nx.selfloop_edges(G))".
