### ISSUE TITLE
Why to `feature_broadcast` and `label_broadcast`?

### ISSUE THREAD

**Issue by PolarisRisingWar** [yifan-h/CS-GNN#7]
I find that when computing feature smoothness, the code uses the function `feature_broadcast` (I find it's to merge feature of a node with its neighbors).
```python
    for i in range(times):
        feats = feature_broadcast(feats, G_org)
```
I find the formula in paper just used original feats with normalization. So I wonder why we need to calculate this feature broadcast?  
The similar problem is on `label_broadcast`, which I think it's to remove some edges randomly. Why we need to do that?

**Comment by yifan-h** [comment]
Hi,

You can find a parameter "time=0". This parameter is for us to research how fast smoothness decreases with broadcast time. Normally you can ignore that since the defualt value is 0.
